### PR TITLE
Added SameTree.java and SameTreeTest.java

### PR DESCRIPTION
**Pull request by dinitrogen-tetroxide**
Issue #91

### CODE REVIEW

**Comment by dinitrogen-tetroxide** [comment]
Oh snap, just realized I forgot to add a parameter. Let me fix that.

**Comment by dinitrogen-tetroxide** [comment]
Terribly sorry about that, I didn't realize that new commits affect the pull request. Sorry about that.

**Review by kenshin579 — APPROVED** [review]
Well, done. 

After merged your code, I will rearrange your comments to make consistent with other file. 

Good Job!!

**Comment by dinitrogen-tetroxide** [comment]
Thank you!

**Pull request merged**
